version: '2'
services:

  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./code/back-end:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
      - "SWOOLE_HTTP_HOST=0.0.0.0"
      - "SWOOLE_HTTP_PORT=80"
      - "CACHE_DRIVER=redis"
    ports:
      - 8080:80

  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "QUEUE_DRIVER=redis"
      - "BROADCAST_DRIVER=redis"
      - "SESSION_DRIVER=redis"
    ports:
      - 33061:3306

  redis:
    image: redis:latest

volumes:
  dbdata: